version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres16
    restart: unless-stopped
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpassword}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5444:5444" # 他のサービスとポートが競合しないように変更
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-appdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    networks:
      - postgres-net

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      TZ: Asia/Tokyo
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-adminpass}
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - postgres-net

volumes:
  pg_data:
    name: drizzle-experimental-pgdata

networks:
  postgres-net: